language: bash
services: docker
before_install:
  - cd ItauFileManager/
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push leandropldev/mysql-itaufilemanagerdb;
    docker push leandropldev/itau-file-manager;
  on:
    branch: master
notifications:
  email: false