version: '3.4'
services:
  ItauFileManager:
    image: leandropldev/itau-file-manager
    restart: always
    build: ./ItauFileManager
    working_dir: /ItauFileManager
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./ItauFileManager:/ItauFileManager
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    networks:
      - itau-network
networks:
    itau-network:
        driver: bridge