version: '3.4'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: itaufilemanagerdb
    ports:
      - "3308:3306"
    networks:
      - itau-network
  ItauFileManager:
    image: leandropldev/itau-file-manager
    restart: always
    build: ./ItauFileManager
    working_dir: /ItauFileManager
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./RestWithSpringBootUdemy:/RestWithSpringBootUdemy
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - itau-network
networks:
    itau-network:
        driver: bridge